[2024-02-20T15:11:10.964+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: etl_reddit_pipeline.reddit_extraction scheduled__2024-02-19T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
